#!/usr/bin/env python3
"""Regenerate Unicode terminal-width intervals using Python's pinned Unicode database.

The tables avoid relying on wchar_t size or platform wcwidth availability. Ambiguous-width
characters use one cell; combining marks, format characters, and Hangul trailing jamo use zero.
Unicode property data is covered by LICENSES/Unicode-3.0.txt.
"""

from pathlib import Path
import subprocess
import unicodedata


UNICODE_VERSION = "16.0.0"


def width(codepoint: int) -> int:
    character = chr(codepoint)
    category = unicodedata.category(character)
    if category in {"Cc", "Cs", "Cn"}:
        return -1
    if category in {"Mn", "Me", "Cf"} or 0x1160 <= codepoint <= 0x11FF:
        return 0
    if unicodedata.east_asian_width(character) in {"W", "F"}:
        return 2
    return 1


def intervals(target: int) -> list[tuple[int, int]]:
    result = []
    start = None
    for codepoint in range(0x110001):
        matches = codepoint < 0x110000 and width(codepoint) == target
        if matches and start is None:
            start = codepoint
        elif not matches and start is not None:
            result.append((start, codepoint - 1))
            start = None
    return result


def main() -> None:
    if unicodedata.unidata_version != UNICODE_VERSION:
        raise SystemExit(f"requires Unicode {UNICODE_VERSION}, found {unicodedata.unidata_version}")
    lines = [
        "/* SPDX-License-Identifier: MIT */",
        "#ifndef HAX_TEXT_UNICODE_WIDTH_DATA_H",
        "#define HAX_TEXT_UNICODE_WIDTH_DATA_H",
        "",
        "/* Generated by scripts/gen_unicode_width.py from Unicode " + UNICODE_VERSION + ".",
        " * Unicode property data is licensed under LICENSES/Unicode-3.0.txt. */",
        "",
    ]
    for name, cells in [("NONPRINTABLE", -1), ("ZERO_WIDTH", 0), ("WIDE", 2)]:
        lines.append(f"static const struct unicode_interval {name}[] = {{")
        lines.extend(f"    {{0x{start:X}, 0x{end:X}}}," for start, end in intervals(cells))
        lines.extend(["};", ""])
    lines.append("#endif /* HAX_TEXT_UNICODE_WIDTH_DATA_H */")
    root = Path(__file__).resolve().parent.parent
    output = root / "src/text/unicode_width_data.h"
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    subprocess.run(["clang-format", "-i", str(output)], check=True)


if __name__ == "__main__":
    main()
